### ISSUE TITLE
config and route cache error after installing breezy

### ISSUE THREAD

**Issue by ziming** [jeffgreco13/filament-breezy#104]
After installing breezy, when i deploy to production, i have been getting the following errors when running the caching commands

artisan config:cache
Your configuration files are not serializable.

artisan route:cache
Unable to prepare route [password/reset] for serialization. Another route has already been assigned name [password.request].

**Comment by jeffgreco13** [comment]
@ziming do you have another auth package installed?

**Comment by ziming** [comment]
is laravel/ui an auth package?

**Comment by jeffgreco13** [comment]
Yes it is if you installed it with `--auth`
It's not recommended to use both the Laravel auth package and Filament Breezy because they have collisions with routes.
In the latest release v1.4.1.2 you can customize the route prefix so it does not interfere with laravel/ui but WARNING: if you do this then Breezy's password reset and email verification routes will still lead to `password.reset` and `password.verify`

Breezy was created to be the only auth solution needed, usually when devs are using Filament Admin as the app UI. It's not recommended to use Breezy with Laravel Auth.

**Comment by howdu** [comment]
I too came across this. Could do with a bigger warning that it won't work with Jetstream(Fortify)

**Comment by jeffgreco13** [comment]
@howdu thanks for your note. I think you're correct, if devs are still missing the note further down the README, I'll had a bigger note higher up.
