### ISSUE TITLE
[feature request] Password expiration feature

### ISSUE THREAD

**Issue by daar** [jeffgreco13/filament-breezy#154]
The current package lacks functionality that automatically expires passwords, which is crucial for enhancing the security of user accounts. I propose to address this by implementing a password expiration feature to enforce regular password updates and reduce the risk of unauthorized access. Password expiration is a widely accepted security practice that prompts users to change their passwords regularly, thereby minimizing the impact of compromised or weak passwords.

To overcome this limitation and encourage better security practices, I recommend implementing a password expiration function with the following features:

* Introduce a configuration option to enable password expiration
* Introduce a configuration option to specify the duration (in days) for password validity
* Introduce a configuration option to enable password expiration notification (none, mail, database as an array of options)
* Introduce a configuration option to specify the notification period (in days) for password expiration. This option will take an array of notification days to allow for multiple notifications to be sent.
* Develop a notification mechanism to alert users when their password expiration date is approaching. The notification methods will support DB notifications and email.
* Implement middleware that checks the users.updated_at field and redirects users to a password reset page when necessary.

If you are interested in contributing to the development of this feature or have any suggestions, please leave your comments on this issue.

**Comment by daar** [comment]
I'm planning to working on this issue here : https://github.com/daar/filament-breezy

**Comment by ankkk** [comment]
So, you might think that forcing people to change their password every so often is a great way to keep things secure. But actually, the National Institute of Standards and Technology (NIST) says that’s not the case anymore. Password expiration policies don’t really do much to make passwords stronger, and can even make them weaker if people are constantly coming up with new ones that are easy to guess.
So, instead of relying on password expiration, it’s better to encourage people to choose strong and unique passwords, use two-factor authentication, and keep an eye out for any weird activity on their accounts. That way, you can keep things safe without making everyone change their password every other week.

Section: 5.1.1.2 Memorized Secret Verifiers:

https://nvlpubs.nist.gov/nistpubs/SpecialPublications/NIST.SP.800-63b.pdf

**Comment by daar** [comment]
Absolutely, you're right! Strong passwords and 2FA are widely acknowledged as effective means of safeguarding data. However, there may be scenarios where implementing 2FA is impractical, particularly when collaborating with individuals who have limited experience with computers. In such situations, incorporating password expiration can provide an alternative layer of security by ensuring that passwords are regularly updated, thereby reducing the risk of compromised accounts.
Laravel provides various validation methods for passwords, that assess the strength of passwords and checks whether a provided password is uncompromised. By combining these strong passwords with additional security measures such as password expiration or 2FA, we have all the tools in place to keep data secured.

**Comment by jeffgreco13** [comment]
This will be worked on in v2, to some degree, and will be released sometime after Filament v3 stable is released in August.
I won't implement this in v1, as I consider v1 to be feature complete.

Check for updates to the repo!
