### ISSUE TITLE
Anybody added Spatie Welcome Notification?

### ISSUE THREAD

**Issue by malle-pietje** [jeffgreco13/filament-breezy#162]
Using the Issues here because Discussions are unavailable.

I am looking to add Spatie Welcome Notification package because I believe it makes sense to send an email to new users created by an admin to allow them to set their own password.

Here’s the package:
https://github.com/spatie/laravel-welcome-notification

Since this is my first Filament project (have already used plain Laravel and Backpack several times), any tips/guidance on how to do this are welcome!

**Comment by john-inkesta** [comment]
I'm looking for a similar solution. I've posted a question here before I found your post:
https://discord.com/channels/883083792112300104/935091455280709672
It's a friendly and (usually) active community...

**Comment by malle-pietje** [comment]
> I'm looking for a similar solution. I've posted a question here before I found your post: https://discord.com/channels/883083792112300104/935091455280709672 It's a friendly and (usually) active community...

Thanks, following there as well.

**Comment by jeffgreco13** [comment]
Hi @malle-pietje @john-inkesta 
Have you tried registering a listener on the Registered::class event?
When a new user is registered using Breezy, this event is fired so you could create a new listener that will send the Welcome email.

If you want to create new users from the Admin panel within a UserResource, you can use the Actions documentation to send the welcome email as well.

Going to close this for now and maybe open up discussions.

https://github.com/jeffgreco13/filament-breezy/blob/6d5d73e5b55cbf9758207bd3ba5e58dfd4da4b9e/src/Http/Livewire/Auth/Register.php#L77

**Comment by john-inkesta** [comment]
Heya!

The point is that users aren't allowed to register for themselves. User accounts are always created by other users via Admin Panel.

I ended up creating a new Welcome mail. And implementing my own `ResetPassword` extending the one from the package. Accepting a `&first=1` query param in order to change the text from "Reset password" to "Set password".

But... the challenge with that is that I don't like the short TTL on the reset link in the mail. If you triggered the reset password mail yourself, you can easily react within the hour. But if someone else created your account, it could take days before you end up reading that mail. So I'm going back to a simpler Welcome mail without link, instructing them to use the forgot-password link.

Thanks for an awesome package @jeffgreco13 !

**Comment by malle-pietje** [comment]
@jeffgreco13 Thanks for the pointers; it probably makes more sense for me to take the same approach as @john-inkesta instead of using the Spatie package.
