### ISSUE TITLE
Avatar visible during 2FA form entry

### ISSUE THREAD

**Issue by mikewink** [jeffgreco13/filament-breezy#211]
Hi Jeff,

Thank you very much for your package/plugin. It made securing my application much easier. It works well too. There is just one little thing.

When I log in, and the form to enter my OTP is shown, I can already see the avatar image. This is not a big deal, but I am sure it is unintended. 

Ohh, and is it normal that when deleting the avatar image from the profile, the image does not get deleted either?

Best regards,

Mike

**Comment by jeffgreco13** [comment]
hi @mikewink
This happens because the Two Factor Authentication redirect happens after the initial username/password authentication. Technically, the user is logged in but cannot use the application without the 2FA code, however they can logout from this user menu if needed.

Breezy uses the SimplePage layout that comes with Filament and this is the default functionality.

**Comment by mikewink** [comment]
Hi Jeff, 

Thank you very much for the update. I will adjust it myself then. 🤓👍🏼
